### PR TITLE
mapped: implement findall_long

### PR DESCRIPTION
**Pull request by victorbenichoux**
Currently, the `Mapped` matcher only implements the `anchored` matching mode.

Here I implement the `findall_longest` for Mapped matcher, and rewrite tests previously only running on a `NoAho` object to run with a `Mapped` object.

### CODE REVIEW

**Comment by pquentin** [comment]
Wow, nice work. It could take some time to review. Is the goal here to only end up with the Mapped interface?

**Comment by victorbenichoux** [comment]
I don't think we want to remove the `NoAho` interface. We could if we could make sure that Python frees the memory created during Trie construction, in which case we could write/load during `NoAho.compile`.

In the meantime, I figure that only supporting `anchored` matching with the `Mapped` trie is an unwarranted limitation. Indeed, the `anchored` mode is a special case of the `longest` mode.

The implementation here is very straighforward and essentially a copy of what is done in the `NoAho` case, simply using the primitives of `Mapped`.

**Comment by pquentin** [comment]
@victorbenichoux The reason I haven't reviewed yet is that I need to understand AhoCorasick + our current implementation + yours to understand the tradeoffs we're making. In particular, I don't know where we're using naive algorithms and where we're not. (It's not necessarily bad, as naive implementations can be faster in practive.)

**Comment by ldeflandre** [comment]
We stopped maintaining this fork and moved to this one sorry:
https://github.com/Cornerstone-OnDemand/noaho

Please reopen the PR if it is still needed/valid.

**Pull request closed without merging**
