### PR TITLE
Support Python 3.7 to 3.11, drop 3.6

### PR DESCRIPTION
**Pull request by pquentin**
Closes #8

### CODE REVIEW

**Comment by victorbenichoux** [comment]
I think it makes sense thanks 👍

**Comment by pquentin** [comment]
Thanks! Not sure if this was meant to be an approval but I don't have the rights to merge this :)

**Comment by victorbenichoux** [comment]
> Thanks! Not sure if this was meant to be an approval but I don't have the rights to merge this :)

I don't either... It seemed to me that you could (you merged this other PR https://github.com/clustree/noahong/pull/6)

**Comment by pquentin** [comment]
Yeah but I was employed there at the time. Pinging @NicolasCarrezCSOD

**Comment by antoinejeannot** [comment]
Hi guys, just came across this conversation and this reminds me good times!

FYI noahong is still a bit maintained here if that helps: https://github.com/Cornerstone-OnDemand/noaho 
At least with the support of new Python versions, the removal of old ones, the setup.cfg fix etc.

In the meantime, I guess @ldeflandre could help out since he is the only one left who might have write access!

**Comment by pquentin** [comment]
Oops. Can you point to the other repo in the README and archive this one?

**Pull request closed without merging**
